// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0-devel
// 	protoc        v3.17.3
// source: stackexchange/protos/RedisMessage.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace    string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	EventName    string   `protobuf:"bytes,2,opt,name=eventName,proto3" json:"eventName,omitempty"`
	ExceptSender string   `protobuf:"bytes,3,opt,name=exceptSender,proto3" json:"exceptSender,omitempty"`
	To           []string `protobuf:"bytes,4,rep,name=to,proto3" json:"to,omitempty"`
	Body         []byte   `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Token        string   `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`        //for askServer
	ToClient     bool     `protobuf:"varint,7,opt,name=toClient,proto3" json:"toClient,omitempty"` //for write Client
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stackexchange_protos_RedisMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_protos_RedisMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_stackexchange_protos_RedisMessage_proto_rawDescGZIP(), []int{0}
}

func (x *ServerMessage) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ServerMessage) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *ServerMessage) GetExceptSender() string {
	if x != nil {
		return x.ExceptSender
	}
	return ""
}

func (x *ServerMessage) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ServerMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerMessage) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ServerMessage) GetToClient() bool {
	if x != nil {
		return x.ToClient
	}
	return false
}

type ReplyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*ReplyMessage_Body
	//	*ReplyMessage_ErrorCode
	Data isReplyMessage_Data `protobuf_oneof:"data"`
}

func (x *ReplyMessage) Reset() {
	*x = ReplyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stackexchange_protos_RedisMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMessage) ProtoMessage() {}

func (x *ReplyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_stackexchange_protos_RedisMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMessage.ProtoReflect.Descriptor instead.
func (*ReplyMessage) Descriptor() ([]byte, []int) {
	return file_stackexchange_protos_RedisMessage_proto_rawDescGZIP(), []int{1}
}

func (m *ReplyMessage) GetData() isReplyMessage_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *ReplyMessage) GetBody() []byte {
	if x, ok := x.GetData().(*ReplyMessage_Body); ok {
		return x.Body
	}
	return nil
}

func (x *ReplyMessage) GetErrorCode() uint32 {
	if x, ok := x.GetData().(*ReplyMessage_ErrorCode); ok {
		return x.ErrorCode
	}
	return 0
}

type isReplyMessage_Data interface {
	isReplyMessage_Data()
}

type ReplyMessage_Body struct {
	Body []byte `protobuf:"bytes,1,opt,name=body,proto3,oneof"`
}

type ReplyMessage_ErrorCode struct {
	ErrorCode uint32 `protobuf:"varint,2,opt,name=errorCode,proto3,oneof"`
}

func (*ReplyMessage_Body) isReplyMessage_Data() {}

func (*ReplyMessage_ErrorCode) isReplyMessage_Data() {}

var File_stackexchange_protos_RedisMessage_proto protoreflect.FileDescriptor

var file_stackexchange_protos_RedisMessage_proto_rawDesc = []byte{
	0x0a, 0x27, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x52, 0x65, 0x64, 0x69, 0x73, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc5, 0x01, 0x0a, 0x0d, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x78, 0x63, 0x65, 0x70,
	0x74, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65,
	0x78, 0x63, 0x65, 0x70, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x74,
	0x6f, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x74, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x22, 0x4c, 0x0a, 0x0c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x14, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48,
	0x00, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x1e, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x09, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42,
	0x09, 0x5a, 0x07, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_stackexchange_protos_RedisMessage_proto_rawDescOnce sync.Once
	file_stackexchange_protos_RedisMessage_proto_rawDescData = file_stackexchange_protos_RedisMessage_proto_rawDesc
)

func file_stackexchange_protos_RedisMessage_proto_rawDescGZIP() []byte {
	file_stackexchange_protos_RedisMessage_proto_rawDescOnce.Do(func() {
		file_stackexchange_protos_RedisMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_stackexchange_protos_RedisMessage_proto_rawDescData)
	})
	return file_stackexchange_protos_RedisMessage_proto_rawDescData
}

var file_stackexchange_protos_RedisMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stackexchange_protos_RedisMessage_proto_goTypes = []interface{}{
	(*ServerMessage)(nil), // 0: ServerMessage
	(*ReplyMessage)(nil),  // 1: ReplyMessage
}
var file_stackexchange_protos_RedisMessage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stackexchange_protos_RedisMessage_proto_init() }
func file_stackexchange_protos_RedisMessage_proto_init() {
	if File_stackexchange_protos_RedisMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stackexchange_protos_RedisMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stackexchange_protos_RedisMessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_stackexchange_protos_RedisMessage_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ReplyMessage_Body)(nil),
		(*ReplyMessage_ErrorCode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stackexchange_protos_RedisMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stackexchange_protos_RedisMessage_proto_goTypes,
		DependencyIndexes: file_stackexchange_protos_RedisMessage_proto_depIdxs,
		MessageInfos:      file_stackexchange_protos_RedisMessage_proto_msgTypes,
	}.Build()
	File_stackexchange_protos_RedisMessage_proto = out.File
	file_stackexchange_protos_RedisMessage_proto_rawDesc = nil
	file_stackexchange_protos_RedisMessage_proto_goTypes = nil
	file_stackexchange_protos_RedisMessage_proto_depIdxs = nil
}
